---
- hosts: runner
  gather_facts: no
  ignore_errors: yes
  become: yes
  tasks:
    - name: unregister runners
      shell: >
        docker exec gitlab-multirunner
        gitlab-ci-multi-runner unregister --all-runners

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: disassociate floating ip from runner VM
      os_floating_ip:
        server: "{{ env_name }}"
        floating_ip_address: "{{ runner_public_ip }}"
        state: absent
    - name: remove runner stack
      os_stack:
        name: "{{ env_name }}"
        state: absent
