---
- hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
    - name: Place SSH private key on RAM disk
      copy:
        content: "{{ runner_vm_ssh_key }}"
        dest: "/dev/shm/id_rsa_gitlab_runner"
        owner: "{{ ansible_user_id }}"
        mode: 0600

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Build runner Heat stack
      os_stack:
        name: "{{ env_name|default('gitlab-runner') }}"
        state: present
        template: "files/gitlab-runner-stack.yml"
        wait: yes
        parameters:
          env_name: "{{ env_name|default('gitlab-runner') }}"
          runner_vm_image: "{{ runner_vm_image|default('CentOS-7') }}"
          runner_vm_flavor: "{{ runner_vm_flavor|default('standard.tiny') }}"
          runner_vm_network: "{{ runner_vm_network }}"
          key_name: "{{ key_name }}"
          secgroup_runner_vm_rules: "{{ secgroup_runner_vm_rules }}"
          volume_runner_vm_size: "{{ volume_runner_vm_size }}"
          runner_ssh_key_rsa_private: "{{ ssh_key_rsa_private|default('') }}"
          runner_ssh_key_rsa_public: "{{ ssh_key_rsa_public|default('') }}"
          runner_ssh_key_ecdsa_private: "{{ ssh_key_ecdsa_private|default('') }}"
          runner_ssh_key_ecdsa_public: "{{ ssh_key_ecdsa_public|default('') }}"
    - name: Associate floating IP with runner VM
      os_floating_ip:
        server: "{{ env_name }}"
        floating_ip_address: "{{ runner_public_ip }}"
    - name: Refresh dynamic inventory
      meta: refresh_inventory

- hosts: runner
  gather_facts: no
  tasks:
    - name: Wait for SSH to work
      shell: >
        ssh -i /dev/shm/id_rsa_gitlab_runner
        {{ ansible_ssh_user }}@{{ ansible_ssh_host }}
        'echo success'
      register: result
      until: result.stdout.find('success') != -1
      retries: 30
      delay: 5
      changed_when: false
      delegate_to: localhost

- hosts: runner
  become: True
  tasks:
    - name: create /dev/shm/secret
      file:
        path: /dev/shm/secret
        state: directory

    - name: initialize secrets in /dev/shm/secret
      copy:
        src: "{{ item.src|default('/dev/shm/secret/' + item.name) }}"
        dest: "/dev/shm/secret/{{ item.name }}"
        mode: "{{ item.mode|default(omit) }}"
        owner: "{{ item.owner|default(omit) }}"
        group: "{{ item.group|default(omit) }}"
      with_items: "{{ runner_secrets|default([]) }}"

- hosts: runner
  roles:
    - ansible-role-users
    - gitlab-runner
