---
heat_template_version: newton

description: >
  GitLab runner stack with one VM and one volume.

parameters:
  env_name:
    description: >
      A name for this runner environment to be used for filtering by a dynamic
      inventory script and as a name for the runner VM.
    type: string
  runner_vm_image:
    description: >
      The name or ID of the image to use for the runner VM.
    type: string
  runner_vm_flavor:
    description: >
      The flavor to use for the runner VM.
    type: string
  runner_vm_network:
    description: >
      Which existing network the runner VM should be connected to.
    type: string
  key_name:
    description: >
      Which SSH public key to place on the runner VM.
    type: string
  secgroup_runner_vm_rules:
    description: >
      Rules for the runner VM security group.
    type: json
  volume_runner_vm_size:
    description: >
      How big the volume attached to the runner VM should be.
    type: string
  runner_ssh_key_rsa_private:
    description: >
      Preconfigured RSA host private key
    type: string
    default: ''
  runner_ssh_key_rsa_public:
    description: >
      Preconfigured RSA host public key
    type: string
    default: ''
  runner_ssh_key_ecdsa_private:
    description: >
      Preconfigured ECDSA host private key
    type: string
    default: ''
  runner_ssh_key_ecdsa_public:
    description: >
      Preconfigured ECDSA host public key
    type: string
    default: ''

resources:
  cloud_config_ssh_keys:
    # this resource demonstrates multiple cloud-config resources
    # with a merge_how strategy
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        ssh_keys:
          rsa_private: { get_param: runner_ssh_key_rsa_private }
          rsa_public: { get_param: runner_ssh_key_rsa_public }
          ecdsa_private: { get_param: runner_ssh_key_ecdsa_private }
          ecdsa_public: { get_param: runner_ssh_key_ecdsa_public }

  runner_vm:
    type: OS::Nova::Server
    properties:
      name: { get_param: env_name }
      image: { get_param: runner_vm_image }
      flavor: { get_param: runner_vm_flavor }
      networks:
        - network: { get_param: runner_vm_network }
      metadata:
        group: "runner"
        stack: { get_param: env_name }
      key_name: { get_param: key_name }
      security_groups:
        - { get_resource: secgroup_runner_vm }
      user_data_format: RAW
      user_data:
        get_resource: cloud_config_ssh_keys

  secgroup_runner_vm:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: env_name-name_suffix
          params:
            env_name: { get_param: env_name }
            name_suffix: "secgroup"
      rules: { get_param: secgroup_runner_vm_rules }

  volume_runner_vm:
    type: OS::Cinder::Volume
    properties:
      name:
        list_join: ['-', [{ get_param: env_name }, "volume"]]
      size: { get_param: volume_runner_vm_size }

  volume_attachment_runner_vm:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: runner_vm }
      volume_id: { get_resource: volume_runner_vm }

outputs:
